//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRLAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Career
    {
        public int CareerID { get; set; }
        public string PlayerID { get; set; }
        public string TeamID { get; set; }
        public System.DateTime StartYear { get; set; }
        public Nullable<System.DateTime> EndYear { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
    }
}
