//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRLAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public string GameID { get; set; }
        //public Nullable<System.DateTime> GameDate { get; set; }
        public Nullable<System.DateTime> GameDate { get; set; }
        public Nullable<byte> GameWeek { get; set; }
        public string HomeTeamID { get; set; }
        public string AwayTeamID { get; set; }
        public Nullable<short> HomeTeamScore { get; set; }
        public Nullable<short> AwayTeamScore { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
