//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRLAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perform
    {
        public string PerformID { get; set; }
        public string TeamID { get; set; }
        public int Points { get; set; }
        public short Wins { get; set; }
        public short Draws { get; set; }
        public short Losts { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
